<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Who a quest is for, what order it asks for, and what the walker gets back (IP-145).
 *
 * Three changes in one migration because all three land on `quests` /
 * `quest_enrollments`, and `docker/entrypoint.sh` migrates on container boot, so
 * three separate migrations would be three chances to take the API down.
 *
 * EVERY CHANGE IS ADDITIVE AND DEFAULTED, on the same rule Version20260813170000
 * set: every existing row and every deployed client keeps the behaviour it has.
 *
 * 1. `quests.audience`
 * --------------------
 * DEFAULT 'public', so no quest written before today changes. 'operator' means the
 * quest is filtered OUT of the listing for anyone without the role, and refused on
 * start. It is deliberately NOT a new `QuestAvailability` reason: a reason would
 * tell a participant that a withheld quest exists, which is worse than not showing
 * it. Filtering leaks nothing.
 *
 * Before this column the only gate available was the availability window, and it
 * was being used as one: on 2026-09-01 `Survey loop (tracked)` was kept away from
 * students by closing `available_to` the same evening. That is a time gate
 * standing in for a user gate and it does not scale past one operator take.
 *
 * 2. `quests.route_policy` and `quest_enrollments.realised_steps`
 * ---------------------------------------------------------------
 * NULL route_policy means the declared step order, which is what every quest does
 * today. A `{"mode":"pool","routes":[[key,...],...]}` policy carries routes that
 * were generated by `monad-knowledge lab quest-build`, NOT computed here.
 *
 * That split is the point. The rule that keeps a walk from crossing a wall lives
 * in `monad_knowledge/lab/placements.py`, which reads PostGIS; this backend has no
 * view of PostGIS and must not grow a second implementation of that rule. On
 * `fiit-ground-0` the two reading rooms have marker cards 1.2 m apart through
 * concrete while the openings are at x = 1.24 m and x = 10.60 m, so the tempting
 * leg is the impossible one, and an unwalkable leg still renders as a short line
 * on a plan. One implementation, or the bug comes back on one side only.
 *
 * `realised_steps` records what a given enrollment was actually asked to walk. It
 * stores the SEQUENCE and not a random seed, because a seed only reproduces an
 * order against a frozen generator, and that generator is not frozen: it gained
 * door awareness on 2026-09-01 and will change again.
 *
 * 3. `quest_enrollments.points_awarded` / `awarded_at`
 * ----------------------------------------------------
 * Before this there was no ledger at all. `QuestController::completeQuest()`
 * returned `$enrollment->getQuest()->getPoints()` in the response and stored
 * nothing, `users` had no points column, and the app printed a score nobody ever
 * received.
 *
 * Frozen at completion rather than derived, because `quests.points` is mutable and
 * a derived total silently rewrites history the first time a quest is re-valued.
 *
 * THE BACKFILL BELOW IS A RECONSTRUCTION, NOT A RECORD. It stamps every already
 * completed enrollment with the quest's CURRENT value, because nothing ever
 * recorded what those walkers were actually promised. It is the best available
 * answer and it is not authoritative; anything reading these rows for the
 * pre/post gamification comparison (IP-145 Phase 5) must exclude rows whose
 * `awarded_at` equals their `completed_at` to the second, which is the signature
 * of a backfilled row rather than a stamped one.
 */
final class Version20260901150000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'IP-145: quest audience, per-enrollment realised route, and a frozen points ledger';
    }

    public function up(Schema $schema): void
    {
        // ── 1. audience ──────────────────────────────────────────────────────
        $this->addSql("ALTER TABLE quests ADD audience VARCHAR(16) DEFAULT 'public' NOT NULL");
        $this->addSql(
            "COMMENT ON COLUMN quests.audience IS "
            ."'public|operator. An operator quest is filtered out of the listing and refused on "
            ."start; it is never reported as a QuestAvailability reason, because a reason "
            ."discloses that a withheld quest exists.'"
        );
        // Every listing query filters on this, and on a table this small the index earns its
        // keep only because the filter runs on the participant hot path.
        $this->addSql('CREATE INDEX quest_audience_idx ON quests (audience)');

        // ── 2. route policy and the realised route ───────────────────────────
        $this->addSql('ALTER TABLE quests ADD route_policy JSON DEFAULT NULL');
        $this->addSql(
            "COMMENT ON COLUMN quests.route_policy IS "
            ."'NULL or {mode:fixed} = the declared step order. {mode:pool,routes:[[key,...]]} "
            ."carries routes pre-generated by lab quest-build; this backend never computes one.'"
        );

        $this->addSql('ALTER TABLE quest_enrollments ADD realised_steps JSON DEFAULT NULL');
        $this->addSql(
            "COMMENT ON COLUMN quest_enrollments.realised_steps IS "
            ."'The target keys this enrollment was actually asked to walk, in order. NULL means "
            ."the quest declared order was served. The SEQUENCE is stored rather than a seed: a "
            ."seed only reproduces against a frozen generator, and ours is not frozen.'"
        );

        // ── 3. the ledger ────────────────────────────────────────────────────
        $this->addSql('ALTER TABLE quest_enrollments ADD points_awarded DOUBLE PRECISION DEFAULT NULL');
        $this->addSql('ALTER TABLE quest_enrollments ADD awarded_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql(
            "COMMENT ON COLUMN quest_enrollments.points_awarded IS "
            ."'Frozen at the transition to completed, from quests.points as it then stood. Never "
            ."recomputed: re-valuing a quest must not rewrite what a past completion was worth.'"
        );
        $this->addSql(
            "COMMENT ON COLUMN quest_enrollments.awarded_at IS "
            ."'(DC2Type:datetime_immutable) When the award was frozen. Equal to completed_at to "
            ."the second means the row was BACKFILLED by Version20260901150000, not stamped.'"
        );
        // A user total is SUM(points_awarded) over their completed enrollments.
        $this->addSql('CREATE INDEX enrollment_user_awarded_idx ON quest_enrollments (user_id, awarded_at)');

        // The reconstruction. See the class docblock: this is not what those walkers
        // were promised, because nothing recorded that.
        $this->addSql(<<<'SQL'
            UPDATE quest_enrollments e
               SET points_awarded = q.points,
                   awarded_at     = e.completed_at
              FROM quests q
             WHERE q.id = e.quest_id
               AND e.status = 'completed'
               AND e.completed_at IS NOT NULL
               AND e.points_awarded IS NULL
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP INDEX enrollment_user_awarded_idx');
        $this->addSql('ALTER TABLE quest_enrollments DROP awarded_at');
        $this->addSql('ALTER TABLE quest_enrollments DROP points_awarded');
        $this->addSql('ALTER TABLE quest_enrollments DROP realised_steps');
        $this->addSql('ALTER TABLE quests DROP route_policy');
        $this->addSql('DROP INDEX quest_audience_idx');
        $this->addSql('ALTER TABLE quests DROP audience');
    }
}
