<?php

namespace App\Quest;

use App\Entity\QuestStep;

/**
 * Turn a quest's declared steps into the sequence ONE enrollment was asked to walk (IP-145).
 *
 * A pooled quest declares every legal target — all 35 surveyed points on `fiit-ground-0` —
 * and each enrollment draws a subset in an order chosen at start. This is the only place that
 * knows how to project the first onto the second.
 *
 * IT SELECTS, IT NEVER INVENTS. The routes were generated by
 * `monad-knowledge lab quest-build`, which owns the rule that keeps a leg from crossing a
 * wall and reads PostGIS to do it. Nothing here computes geometry, and a key naming no
 * declared step is dropped rather than guessed at.
 *
 * The rule that makes it safe: an unusable route degrades to the declared order, never to a
 * partial one. A walker given three of their twenty stops has a broken quest that looks
 * finished, which is worse than a walker given the full declared set.
 */
final class RealisedRoute
{
    /**
     * The steps to serve, in order.
     *
     * @param list<QuestStep> $steps       every declared step, any order
     * @param list<string>|null $realised  target keys this enrollment drew, or null
     * @return list<QuestStep>
     */
    public static function apply(array $steps, ?array $realised): array
    {
        usort($steps, static fn (QuestStep $a, QuestStep $b): int => $a->getOrder() <=> $b->getOrder());

        if ($realised === null || $realised === []) {
            return $steps;
        }

        // Walk the sorted list once and build GROUPS. A `walk_to` carries no target of its
        // own and belongs to the probe that follows it, so a group is "everything since the
        // last probe, up to and including this one". Keying only on the probe would strand
        // every walk_to, which is precisely the bug this loop replaced.
        $opening = [];
        $closing = [];
        $byKey = [];
        $pending = [];
        $started = false;

        foreach ($steps as $step) {
            $type = $step->getType()?->value;
            // The route begins at the first walk_to OR probe, by TYPE and not by whether the
            // step carries a target. Waiting for a target put the first `walk_to` in the
            // preamble, so stop one lost the instruction telling the walker where to go while
            // every other stop kept theirs — a shape that looks right until you count.
            $isRouteStep = $type === 'walk_to' || $type === 'probe';
            if (!$started && !$isRouteStep) {
                $opening[] = $step;
                continue;
            }
            $started = true;

            $key = self::keyOf($step);
            if ($key !== null) {
                $byKey[$key] = [...$pending, $step];
                $pending = [];
                continue;
            }
            $pending[] = $step;
        }
        // Whatever is still pending when the list ends belongs after the last stop.
        $closing = $pending;

        $middle = [];
        foreach ($realised as $key) {
            foreach ($byKey[(string) $key] ?? [] as $step) {
                $middle[] = $step;
            }
        }

        // Degrade whole, not partially. If the route named keys this quest does not declare —
        // a stale pool after a card was re-laid, most likely — serving what matched would be
        // a short quest that looks complete.
        if ($middle === []) {
            return $steps;
        }

        return [...$opening, ...$middle, ...$closing];
    }

    /**
     * The surveyed point a step is about, or null when it is not about one.
     *
     * A probe carries its target's printed payload (`https://…/m/MONAD-FP-01`) and the pool
     * carries bare keys, so the last path segment joins them. Keeping that conversion here,
     * rather than storing keys on the step, means the printed registry stays the single
     * authority on payload grammar.
     *
     * A `walk_to` immediately precedes its probe and carries no target of its own. It is
     * grouped with the probe that follows in {@see apply()}, not keyed here.
     */
    private static function keyOf(QuestStep $step): ?string
    {
        $targets = $step->getConfig()['targets'] ?? null;
        if (!is_array($targets) || $targets === []) {
            return null;
        }
        $value = $targets[0]['value'] ?? null;
        if (!is_string($value) || $value === '') {
            return null;
        }
        $slash = strrchr($value, '/');

        return $slash === false ? $value : substr($slash, 1);
    }
}
